#!/bin/bash
# Manage the committed CloudKit schema snapshot (CloudKit/schema.ckdb).
#
# The schema itself is generated by NSPersistentCloudKitContainer from the
# SwiftData model (SavedLocation), so the model is the source of truth and
# the .ckdb file is a reviewable snapshot of what CloudKit ends up with.
# Record types are NOT auto-created in the Production environment: after any
# model change the schema must be deployed there before the build reaches
# TestFlight, or sync fails silently.
#
#   Scripts/cloudkit-schema.sh export   # snapshot the Development schema into the repo
#   Scripts/cloudkit-schema.sh check    # fail unless Production matches the snapshot
#   Scripts/cloudkit-schema.sh deploy   # import the snapshot into Production (additive only)
#
# Authentication: a CloudKit management token, either saved in the keychain
# (`xcrun cktool save-token`) or passed via the CLOUDKIT_MANAGEMENT_TOKEN
# environment variable (what CI uses). Issue tokens in CloudKit Console under
# Settings > Tokens & Keys; they expire and need reissuing.
set -euo pipefail

TEAM_ID="3Y8APYUG2G"
CONTAINER_ID="iCloud.io.ngs.Tides"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA_FILE="$REPO_ROOT/CloudKit/schema.ckdb"

cktool() {
  xcrun cktool "$@" --team-id "$TEAM_ID" --container-id "$CONTAINER_ID"
}

require_schema_file() {
  if [ ! -f "$SCHEMA_FILE" ]; then
    echo "error: $SCHEMA_FILE does not exist; run '$0 export' and commit it." >&2
    exit 1
  fi
}

case "${1:-}" in
  export)
    mkdir -p "$(dirname "$SCHEMA_FILE")"
    cktool export-schema --environment development --output-file "$SCHEMA_FILE"
    echo "Wrote $SCHEMA_FILE (Development environment). Review the diff and commit it."
    ;;
  check)
    require_schema_file
    production="$(mktemp)"
    trap 'rm -f "$production"' EXIT
    cktool export-schema --environment production --output-file "$production"
    if ! diff -u "$production" "$SCHEMA_FILE"; then
      cat >&2 <<'MSG'
error: The Production CloudKit schema does not match CloudKit/schema.ckdb.
  - If the model changed, deploy first: Scripts/cloudkit-schema.sh deploy
    (or CloudKit Console > Development > Deploy Schema Changes).
  - If Production was changed elsewhere, refresh the snapshot:
    Scripts/cloudkit-schema.sh export, then commit the diff.
MSG
      exit 1
    fi
    echo "Production schema matches CloudKit/schema.ckdb."
    ;;
  deploy)
    require_schema_file
    # --validate validates the file before importing; the import still runs.
    cktool import-schema --environment production --validate --file "$SCHEMA_FILE"
    echo "Deployed $SCHEMA_FILE to Production."
    ;;
  *)
    echo "usage: $0 export|check|deploy" >&2
    exit 64
    ;;
esac
