import Foundation
import Testing
@testable import TidesCore

private struct NodalFixture: Decodable {
    struct Case: Decodable {
        var time: String
        var constituents: [String: Factors]
    }

    struct Factors: Decodable {
        var factor: Double
        var uDeg: Double

        enum CodingKeys: String, CodingKey {
            case factor = "f"
            case uDeg = "u_deg"
        }
    }

    var description: String
    var tolerance: Double
    var cases: [Case]
}

/// Golden fixture: nodal correction factors f/u generated by the Go
/// implementation (tides-api `internal/domain/nodal.go`).
struct NodalFactorsTests {
    @Test
    func factorsMatchGoImplementation() throws {
        let fixture = try FixtureSupport.load(NodalFixture.self, fixture: "nodal_factors")
        #expect(!fixture.cases.isEmpty)

        for testCase in fixture.cases {
            let time = try FixtureSupport.date(rfc3339: testCase.time)
            let hours = time.timeIntervalSince1970 / 3_600.0
            #expect(!testCase.constituents.isEmpty)

            for (name, expected) in testCase.constituents {
                let correction = AstronomicalNodalCorrection.factors(
                    constituent: name,
                    hoursSinceUnixEpoch: hours
                )
                #expect(
                    abs(correction.f - expected.factor) <= fixture.tolerance,
                    "f mismatch for \(name) at \(testCase.time): got \(correction.f), want \(expected.factor)"
                )
                #expect(
                    abs(correction.uDegrees - expected.uDeg) <= fixture.tolerance,
                    "u mismatch for \(name) at \(testCase.time): got \(correction.uDegrees), want \(expected.uDeg)"
                )
            }
        }
    }
}
