import Foundation
import Testing
import TidesCore

private struct PredictionFixture: Decodable {
    var description: String
    var heightToleranceM: Double
    var sets: [PredictionSet]

    enum CodingKeys: String, CodingKey {
        case description
        case heightToleranceM = "height_tolerance_m"
        case sets
    }
}

private struct PredictionSet: Decodable {
    struct Constituent: Decodable {
        var name: String
        var speedDegPerHr: Double
        var amplitudeM: Double
        var phaseDeg: Double
        var equilibriumArgumentDeg: Double

        enum CodingKeys: String, CodingKey {
            case name
            case speedDegPerHr = "speed_deg_per_hr"
            case amplitudeM = "amplitude_m"
            case phaseDeg = "phase_deg"
            case equilibriumArgumentDeg = "equilibrium_argument_deg"
        }
    }

    struct Point: Decodable {
        var time: String
        var heightM: Double

        enum CodingKeys: String, CodingKey {
            case time
            case heightM = "height_m"
        }
    }

    var name: String
    var referenceTime: String
    var mslM: Double
    var constituents: [Constituent]
    var start: String
    var end: String
    var intervalSec: Int
    var predictions: [Point]
    var highs: [Point]
    var lows: [Point]

    enum CodingKeys: String, CodingKey {
        case name
        case referenceTime = "reference_time"
        case mslM = "msl_m"
        case constituents
        case start
        case end
        case intervalSec = "interval_sec"
        case predictions
        case highs
        case lows
    }
}

/// Golden fixture: height series and extrema generated by the Go
/// implementation (tides-api `internal/domain/tide.go` via
/// `GeneratePredictions` / `FindExtrema` / `RefineExtrema`).
struct PredictionFixtureTests {
    /// Extrema tolerances: times within 30 seconds, heights within 1e-4 m.
    private static let extremaTimeToleranceSec = 30.0
    private static let extremaHeightToleranceM = 1e-4

    private func makePredictor(for set: PredictionSet) throws -> TidePredictor {
        let referenceTime = try FixtureSupport.date(rfc3339: set.referenceTime)
        let parameters = HarmonicParameters(
            location: nil,
            stationID: nil,
            source: "fes",
            datum: "MSL",
            mslMeters: set.mslM,
            seabedDepthMeters: nil,
            referenceTime: referenceTime,
            constituents: set.constituents.map {
                HarmonicParameters.Constituent(
                    name: $0.name,
                    speedDegPerHour: $0.speedDegPerHr,
                    amplitudeMeters: $0.amplitudeM,
                    phaseDegrees: $0.phaseDeg,
                    equilibriumArgumentDegrees: $0.equilibriumArgumentDeg
                )
            }
        )
        return TidePredictor(parameters: parameters)
    }

    @Test
    func heightSeriesMatchesGoImplementation() throws {
        let fixture = try FixtureSupport.load(PredictionFixture.self, fixture: "predictions")
        #expect(!fixture.sets.isEmpty)

        for set in fixture.sets {
            let predictor = try makePredictor(for: set)
            let start = try FixtureSupport.date(rfc3339: set.start)
            let end = try FixtureSupport.date(rfc3339: set.end)

            let series = predictor.predictions(
                from: start,
                to: end,
                interval: TimeInterval(set.intervalSec)
            )
            try #require(
                series.count == set.predictions.count,
                "\(set.name): prediction count \(series.count) != \(set.predictions.count)"
            )

            for (got, want) in zip(series, set.predictions) {
                let wantTime = try FixtureSupport.date(rfc3339: want.time)
                #expect(
                    abs(got.time.timeIntervalSince(wantTime)) < 1e-6,
                    "\(set.name): time mismatch \(got.time) != \(want.time)"
                )
                #expect(
                    abs(got.heightMeters - want.heightM) <= fixture.heightToleranceM,
                    "\(set.name) at \(want.time): height \(got.heightMeters), want \(want.heightM)"
                )
            }
        }
    }

    @Test
    func extremaMatchGoImplementation() throws {
        let fixture = try FixtureSupport.load(PredictionFixture.self, fixture: "predictions")

        for set in fixture.sets {
            let predictor = try makePredictor(for: set)
            let start = try FixtureSupport.date(rfc3339: set.start)
            let end = try FixtureSupport.date(rfc3339: set.end)

            let extrema = predictor.extrema(from: start, to: end)

            try expectMatches(extrema.highs, set.highs, label: "\(set.name) highs")
            try expectMatches(extrema.lows, set.lows, label: "\(set.name) lows")
        }
    }

    private func expectMatches(
        _ got: [TideLevel],
        _ want: [PredictionSet.Point],
        label: String
    ) throws {
        try #require(got.count == want.count, "\(label): count \(got.count) != \(want.count)")
        for (actual, expected) in zip(got, want) {
            let wantTime = try FixtureSupport.date(rfc3339: expected.time)
            #expect(
                abs(actual.time.timeIntervalSince(wantTime)) <= Self.extremaTimeToleranceSec,
                "\(label): time \(actual.time) not within 30s of \(expected.time)"
            )
            #expect(
                abs(actual.heightMeters - expected.heightM) <= Self.extremaHeightToleranceM,
                "\(label) at \(expected.time): height \(actual.heightMeters), want \(expected.heightM)"
            )
        }
    }
}
