name: Release Build and Upload

on:
  push:
    branches: [fastlane]
  # Trigger when CI workflow completes successfully
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master
      - main

  # Manual trigger
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to build"
        required: true
        type: choice
        options:
          - all
          - ios
          - mac
          - visionos
        default: all
      skip_upload:
        description: "Skip App Store Upload"
        required: false
        type: boolean
        default: false

env:
  # Load all secrets as environment variables
  FASTLANE_SKIP_UPDATE_CHECK: "1"
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: "true"
  PRECHECK_INCLUDE_IN_APP_PURCHASES: "false"
  MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }} # Must be SSH format: git@github.com:user/repo.git
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  PRODUCE_ITC_TEAM_ID: ${{ secrets.PRODUCE_ITC_TEAM_ID }}
  PRODUCE_TEAM_ID: ${{ secrets.PRODUCE_TEAM_ID }}
  MATCH_KEYCHAIN_NAME: tmp.keychain
  CERT_KEYCHAIN_NAME: tmp.keychain
  KEYCHAIN_NAME: tmp.keychain
  MATCH_KEYCHAIN_PASSWORD: tmp
  CERT_KEYCHAIN_PASSWORD: tmp
  KEYCHAIN_PASSWORD: tmp
  MATCH_READONLY: "true"

  # Additional Fastlane settings
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: "600"
  FASTLANE_XCODEBUILD_SETTINGS_RETRIES: "5"

jobs:
  check-ci-status:
    # Only run for workflow_run trigger
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Check CI workflow status
        id: check
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "CI workflow completed successfully"
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "CI workflow did not complete successfully: ${{ github.event.workflow_run.conclusion }}"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  determine-platforms:
    # Determine which platforms to build based on the trigger
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      skip_upload: ${{ steps.set-params.outputs.skip_upload }}
    steps:
      - name: Set parameters
        id: set-params
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "skip_upload=${{ github.event.inputs.skip_upload }}" >> $GITHUB_OUTPUT
          else
            echo "skip_upload=false" >> $GITHUB_OUTPUT
          fi

      - name: Set matrix
        id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.platform }}" == "all" ]]; then
              echo 'matrix=["ios", "mac", "visionos"]' >> $GITHUB_OUTPUT
            else
              echo 'matrix=["${{ github.event.inputs.platform }}"]' >> $GITHUB_OUTPUT
            fi
          else
            # Default for CI completion trigger
            echo 'matrix=["ios", "mac", "visionos"]' >> $GITHUB_OUTPUT
          fi

  release:
    needs: [check-ci-status, determine-platforms]
    if: |
      always() &&
      (
        (github.event_name == 'workflow_dispatch') ||
        (github.event_name == 'push') ||
        (github.event_name == 'workflow_run' && needs.check-ci-status.outputs.should_deploy == 'true')
      )
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.determine-platforms.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        run: ls -l /Applications && sudo xcode-select -s /Applications/Xcode_26.app

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Create CI keychain
        run: bundle exec fastlane create_ci_keychain

      - name: Setup SSH for Match
        env:
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
        run: |
          echo "Setting up SSH with deploy key..."
          mkdir -p ~/.ssh
          echo "$MATCH_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Configure git to use SSH
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Cache Match certificates
        uses: actions/cache@v4
        with:
          path: ~/Library/MobileDevice/Provisioning Profiles
          key: ${{ runner.os }}-certificates-${{ matrix.platform }}-${{ hashFiles('**/Matchfile') }}
          restore-keys: |
            ${{ runner.os }}-certificates-${{ matrix.platform }}-
            ${{ runner.os }}-certificates-

      - name: Install tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist

      - name: Generate Xcode project and workspace
        run: |
          case "${{ matrix.platform }}" in
            ios)
              export TUIST_BUILD_NUMBER="${{ github.run_id }}.1"
              ;;
            mac)
              export TUIST_BUILD_NUMBER="${{ github.run_id }}.2"
              ;;
            visionos)
              export TUIST_BUILD_NUMBER="${{ github.run_id }}.3"
              ;;
          esac
          echo "Using build number: $TUIST_BUILD_NUMBER"
          tuist generate --no-open

      - name: Get version info
        id: version
        run: |
          # Version will be set by Fastlane using GitHub Actions Run ID
          echo "GitHub Actions Run ID: ${{ github.run_id }}"
          # Get current version from Project.swift (Tuist)
          VERSION=$(grep -E 'version *= *"' Project.swift | head -1 | sed -E 's/.*version *= *"([^"]+)".*/\1/' || echo "1.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"
          echo "Build number will be: ${{ github.run_id }}"

      - name: Build release version
        run: |
          echo "Running fastlane ${{ matrix.platform }} release_build with GitHub Actions Run ID: ${{ github.run_id }}"
          bundle exec fastlane ${{ matrix.platform }} release_build

      - name: Upload to App Store Connect
        if: needs.determine-platforms.outputs.skip_upload != 'true'
        run: |
          echo "Running fastlane ${{ matrix.platform }} release_upload..."
          bundle exec fastlane ${{ matrix.platform }} release_upload

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}-${{ github.sha }}
          path: |
            build/release/**/*.ipa
            build/release/**/*.pkg
            fastlane/report.xml
            build/release/**/*.dSYM.zip
          retention-days: 30

      - name: Upload gym logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gym-logs-${{ matrix.platform }}-${{ github.sha }}
          path: |
            /Users/runner/Library/Logs/gym/*.log
            fastlane/report.xml
          retention-days: 7

  create-release:
    needs: [release, determine-platforms]
    if: |
      needs.release.result == 'success' &&
      needs.determine-platforms.outputs.skip_upload != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version info
        id: version
        run: |
          VERSION=$(grep -E 'version *= *"' Project.swift | head -1 | sed -E 's/.*version *= *"([^"]+)".*/\1/' || echo "1.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: release-*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}-${{ github.run_id }}
          name: Release v${{ steps.version.outputs.version }} (Build ${{ github.run_id }})
          draft: false
          prerelease: true
          generate_release_notes: true
          files: |
            artifacts/**/*.ipa
            artifacts/**/*.pkg
            artifacts/**/*.dSYM.zip

  notify:
    needs: [release, create-release, determine-platforms]
    if: |
      always() &&
      needs.determine-platforms.outputs.skip_upload != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification - Success
        if: success() && env.SLACK_WEBHOOK != ''
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK || '' }}
        run: |
          if [ -n "$SLACK_WEBHOOK" ]; then
            curl -X POST "$SLACK_WEBHOOK" \
              -H 'Content-Type: application/json' \
              -d @- <<EOF
          {
            "text": ":rocket: Tides release build successful!",
            "attachments": [{
              "color": "good",
              "fields": [
                {"title": "Build Number", "value": "${{ github.run_id }}", "short": true},
                {"title": "Commit", "value": "${{ github.sha }}", "short": true}
              ]
            }]
          }
          EOF
          fi
        continue-on-error: true

      - name: Slack notification - Failure
        if: failure() && env.SLACK_WEBHOOK != ''
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK || '' }}
        run: |
          if [ -n "$SLACK_WEBHOOK" ]; then
            curl -X POST "$SLACK_WEBHOOK" \
              -H 'Content-Type: application/json' \
              -d @- <<EOF
          {
            "text": ":x: Tides release build failed!",
            "attachments": [{
              "color": "danger",
              "fields": [
                {"title": "Workflow", "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}
              ]
            }]
          }
          EOF
          fi
        continue-on-error: true
